version: 2
updates:
  - package-ecosystem: terraform
    directory: /layers/test
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /modules/submod
    schedule:
      interval: daily
